name: weekly post
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * FRI'
jobs:
  post:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    environment: slack-imas-birthday
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: node weekly.js
        env:
          GOOGLE_API_ENGINE_KEY: ${{ secrets.GOOGLE_API_ENGINE_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SLACK_WEBHOOK_CHANNEL: ${{ secrets.SLACK_WEBHOOK_CHANNEL }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
